# Generated by Django 5.1.3 on 2024-11-12 01:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enfermedades', '0001_initial'),
        ('usuarios', '0002_ubicacion_dispositivo_usuarios_ubicaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enfermedades.enfermedad')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.ubicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busquedas', to=settings.AUTH_USER_MODEL)),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busquedas.imagen')),
            ],
        ),
    ]
