# Generated by Django 5.1.3 on 2024-11-12 04:54

import django.utils.timezone
import usuarios.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_ubicacion_dispositivo_usuarios_ubicaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={},
        ),
        migrations.AlterModelManagers(
            name='usuarios',
            managers=[
                ('objects', usuarios.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='ubicaciones',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='username',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Este Correo electronico ya esta registrado'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
