# Generated by Django 5.1.3 on 2024-11-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuarios_options_alter_usuarios_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
