# Generated by Django 5.1.3 on 2025-02-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuarios_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Este correo electronico ya esta registrado'}, max_length=100, unique=True),
        ),
    ]
