# Generated by Django 5.1.3 on 2024-12-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='fuente',
            field=models.URLField(default='urlexample.com'),
        ),
    ]
